version: '3'
services:
  app:
    platform: linux/amd64
    image: docker.vamgoon.cn:5000/nest-test-01
    build:
      context: .
      dockerfile: Dockerfile
      target: deploy
    ports:
      - 3000:3000
